Record with rospy
nasa/astrobee pull request #344
Opened 2021-11-20 01:57 UTC by marinagmoreira

Given that the current data_bagger uses up to 30% of cpu and the "rosbag record" command uses 0%, I changed the astrobee recorder to call the cmd line.
Removed all the threads, making this single thread.

I basically re-did the astrobee_recorder.cc:
 * translates record options into a "rosbag record" cmd;
 * removed the checks that are already done by "rosbag record" -- left only the checkDisk because there are some horror stories on forums of the entire disk being filled and the system unuseable.
 * does a fork->exec to start the recording process (used popen2 to leave the possibility of reading/writing).
 
Added some comments to the data_bagger, added some checks, and made the function order match the h-file.

- [ ] Test on the robot

2021-11-24 22:33 UTC, marinagmoreira commented
I tested this remotely on bsharp, I recorded the MobNavDockRAW and it was a breeze, still using close to nothin
![Screenshot from 2021-11-24 14-28-46](https://user-images.githubusercontent.com/67443181/143321148-4e709d18-a319-469b-856b-b4a53da718be.png)
g

2021-11-29 18:38 UTC, bcoltin requested changes

2021-11-29 18:38 UTC, bcoltin commented on management/data_bagger/src/astrobee_recorder.cc
> +    execl("/bin/sh", "sh", "-c", command, NULL);
Can the user passes some weird string as a topic that would get parsed to evaluate an arbitrary command? Would be better if we could do exec on rosbag record directly without letting things get interpreted by the shell.

2021-11-29 20:29 UTC, kbrowne15 approved these changes
Once Brian's comment is addressed, it should be good to merge.

2021-12-06 22:29 UTC, bcoltin approved these changes
Thanks!

2021-12-16 18:45 UTC, bcoltin commented
We will test this with the performance script and tune some parameters before merging this.

2022-01-12 21:54 UTC, closed without merging