Add doc and tools for using Theia, and doc formatting
nasa/astrobee pull request #348
Opened 2021-11-30 17:55 UTC by oleg-alexandrov

Changes:

 - Added a wrapper around the Theia tool for building a map. 
 - Fixed some issues in the localization docs to make links to other subpages work well with GitHub's markup. 
 - Updated the bumble calibration for sci cam, haz cam, and extrinsics among these and to nav cam. Did not change the nav cam calibration.

2021-11-30 18:42 UTC, marinagmoreira requested changes

2021-11-30 18:42 UTC, marinagmoreira commented on localization/sparse_mapping/readme.md
> +    astrobee/build/devel/lib/localization_node/merge_bags \
should be astrobee/devel/lib/localization_node/merge_bags according to the default setup

2021-11-30 18:42 UTC, marinagmoreira commented on localization/sparse_mapping/readme.md
> +    astrobee/build/devel/lib/localization_node/extract_image_bag   \
same here

2021-12-01 00:18 UTC, oleg-alexandrov commented
I implemented Marina's suggestions (also in many other places) so that the correct paths to the "devel" directory is used. 

Sorry this pull request became too big.

2021-12-01 23:39 UTC, marinagmoreira approved these changes

2021-12-03 19:16 UTC, merged

2021-12-03 19:17 UTC, oleg-alexandrov commented
I pulled this in myself. I have another pull request to make, and this way staying in the way and was approved.

2021-12-03 19:18 UTC, bcoltin commented
Once it's been approved by a reviewer it's fine to pull it in yourself. Thanks!