Added Zsh Support
nasa/astrobee pull request #366
Opened 2021-12-14 13:17 UTC by Pedro-Roque

Support for Zsh users.

2021-12-14 17:18 UTC, oleg-alexandrov commented on scripts/configure.sh
> +      echo 'if [[ ":$CMAKE_PbREFIX_PATH:" != *":'${cmake_astrobee_path}':"* ]]; then CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:+"$CMAKE_PREFIX_PATH:"}'${cmake_astrobee_path}'"; fi' >> ~/.bashrc
This line has a typo.

2021-12-14 17:18 UTC, oleg-alexandrov commented on scripts/configure.sh
> +        echo 'if [[ ":$CMAKE_PbREFIX_PATH:" != *":'${cmake_astrobee_path}':"* ]]; then CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:+"$CMAKE_PREFIX_PATH:"}'${cmake_astrobee_path}'"; fi' >> ~/.zshrc
This line has a typo.

2021-12-14 22:16 UTC, Pedro-Roque commented
Thanks @oleg-alexandrov , just pushed a typo fix

2021-12-14 22:31 UTC, oleg-alexandrov commented
Thank you.

Running configure.sh will each time add more lines to .zshrc. I hope you can test if that is the case. Then note the logic used with .bashrc where a grep call first checks if the desired line is already in. Maybe you can do something similar and test that this time it does not add lines to .zshrc if already present.

2021-12-15 00:45 UTC, marinagmoreira requested changes

2021-12-15 00:45 UTC, marinagmoreira commented on scripts/configure.sh
> +        echo 'if [[ ":$CMAKE_PREFIX_PATH:" != *":'${cmake_astrobee_path}':"* ]]; then CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:+"$CMAKE_PREFIX_PATH:"}'${cmake_astrobee_path}'"; fi' >> ~/.zshrc
I second Oleg's comment, if you notice we have before those add commands:
 grep -qF ${cmake_astrobee_path} ~/.bashrc ||

2021-12-15 12:23 UTC, Pedro-Roque commented
Yes indeed! I'll add that check in and re-push, thanks for the feedback @oleg-alexandrov and @marinagmoreira!

2021-12-15 14:57 UTC, Pedro-Roque commented
Updated :)

2021-12-15 16:23 UTC, oleg-alexandrov commented
Looks good to me. Did you test that the .zshrc gets updated, and only once?

2021-12-15 18:01 UTC, Pedro-Roque commented
Yes, it did not add anything else to my .zshrc. I also modified the check for Zsh, to only set it if the user $SHELL is Zsh

2021-12-15 18:44 UTC, oleg-alexandrov commented
Sounds good. I will leave it up to Marina to approve and bring in the change.

2021-12-15 21:12 UTC, marinagmoreira approved these changes

2021-12-15 21:17 UTC, Pedro-Roque commented
@marinagmoreira should this be merged? or waiting for @oleg-alexandrov ?

2021-12-15 22:15 UTC, merged