Changes to bot config files and some minor fixes
nasa/astrobee pull request #373
Opened 2021-12-22 20:42 UTC by oleg-alexandrov

This commit changes all the robot config files to reflect a more generic approach of defining relationships between camera transforms. All the camera transforms and timestamp offsets are now relative to nav cam. This is only relevant for ISAAC.

I also put a fix in reading config files so it does not complain when a table is read instead of number for the distortion parameters.  For that, I added to config_reader a function which can peek and see if a field is a number or a table.

I modified the calibration doc to note that nowadays pico_proxy is launched automatically (as long as drivers are launched), but kept the original logic for how to launch it separately if necessary.

Then I fixed a bug in iss.rviz. The sci cam topic should be compressed, otherwise it can't be displayed.

2021-12-22 21:26 UTC, bcoltin requested changes

2021-12-22 21:26 UTC, bcoltin commented on astrobee/config/robots/bsharp.config
> +  nav_cam_to_haz_cam_timestamp_offset = -0.02,
I don't think the geometry section is the best place for time offsets. Maybe in the calibrations section would be better? Or if you have another idea.

2021-12-22 21:58 UTC, oleg-alexandrov commented
Strictly speaking the camera transforms are also calibrated quantities, just like the offsets. But  I see your point. The offsets would probably belong under each camera's intrinsics, further down the config file, in the robot_calibrations subsection. 

I'll implement this tomorrow if there's no further comments.

2021-12-22 22:20 UTC, bcoltin commented
> Strictly speaking the camera transforms are also calibrated quantities, just like the offsets. But I see your point. The offsets would probably belong under each camera's intrinsics, further down the config file, in the robot_calibrations subsection.
> 
> I'll implement this tomorrow if there's no further comments.

Otherwise it looks good to me! Thanks!

2021-12-23 21:20 UTC, oleg-alexandrov commented
I moved the offsets to the robot_calibrations namespace. I checked that the bot files for bumble, honey, queen, and bsharp load well and work as expected, and that the rest follow the same logic (a script was used to consistently convert their format). 

I will merge this once the tests pass.

2021-12-23 21:34 UTC, bcoltin approved these changes

2021-12-23 22:05 UTC, merged