WIP improve documentation in Astrobee command dictionary
nasa/astrobee pull request #54
Opened 2020-10-03 01:46 UTC by trey0

I have always wanted the Astrobee command dictionary to be self-documenting to the point that a new guest scientist or FSW developer could get a clear idea of what each command is intended to be used for, and how it fits into the conops (for example, what are the steps of perching?). With these changes, it should be much closer to that point.

The caveat is that I'm not as close to the code as the FSW team, so some of my documentation might be wrong! In many places, it is based on either ancient memory or a kind of shallow reading of the code.

I recommend starting code review by opening doc/AstrobeeCommandDictionary.html in a browser.

In the schema: Mostly I just changed the "notes" field in many places, which should have no functional effect. In a few places, I also added a "choices" field, documented apparently available choices that weren't listed before, or specified a logical default value where none was present before. These changes propagate to output source files (e.g. cause some new macros to be defined), but again, it looks like they should have no functional effect.

I also updated the schema processing script slightly in the process of getting it to run on my MacBook.

2020-10-16 19:17 UTC, kbrowne15 requested changes

2020-10-17 02:36 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "This command is not implemented. The intent is that it will load a ROS nodelet in the Astrobee flight software.<p/>A note for developers: there is an internal service advertised by th
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:37 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "For internal use only. Unloads a ROS nodelet in Astrobee's flight software. This command is defined only so as to make it available in the system monitor's fault response table. It is
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:37 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Switch Astrobee's localization to use the general-purpose pipeline.<p/>This command is equivalent to calling Admin.switchLocalization with the \"MappedLandmarks\" pipeline, which also
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:37 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Puts Astrobee in hibernate power mode.<p/>An Astrobee that is hibernating can't receive Astrobee API commands. However, it can later be remotely awakened using Admin.wake, if it is on
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:37 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Wakes an Astrobee from a hibernating state (only EPS powered) into a ready state (main processors powered, flight software stack running, ready to receive Astrobee API commands). The
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:38 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "For expert use only. Enables/disables auto-return to the dock. See Mobility.autoReturn.<p/>Note: Currently this flag appears to be ignored.",
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:38 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +          "notes": "The DDS telemetry topic to manage. Note: The \"CommStatus\" topic does not appear to actually be in use."
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:39 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Set camera parameters. This command must be sent while the camera is not recording. Once parameters are set, use Settings.setCameraRecording to start recording.",
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:39 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +          "parent": "Settings.CameraMode"
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:39 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Sets camera streaming live video to the ground on/off.",
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 02:39 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +          "notes": "Applies to streaming and recording. Maximum frame rate varies by camera:<br/>- SciCam: 30 Hz <br/>- NavCam, DockCam: 15 Hz<br/>- HazCam, PerchCam: 5 Hz"
Ok, fixed in https://github.com/trey0/astrobee/commit/ef356efee2945102367626be429e1f183fd033fd

2020-10-17 03:18 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Astrobee move command. Using the default trapezoidal planner, the move has the following steps:<br/>- If not in holonomic mode, the robot rotates to face the target position.<br/>- On
Ok, fixed in https://github.com/trey0/astrobee/commit/8a80326356bb67ab919e23ab2f696670914e96a3

2020-10-17 03:19 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Runs the currently loaded plan. If the plan was previously paused with Plan.pausePlan, this command will resume execution where it previously left off. See plan.setPlan.",
Ok, fixed in https://github.com/trey0/astrobee/commit/8a80326356bb67ab919e23ab2f696670914e96a3

2020-10-17 03:19 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Temporarily pauses the running plan. Execution will resume automatically after the specified duration. See plan.setPlan.",
Ok, fixed in https://github.com/trey0/astrobee/commit/8a80326356bb67ab919e23ab2f696670914e96a3

2020-10-17 03:19 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +      "notes": "Set camera video onboard recording on/off.",
Ok, fixed in https://github.com/trey0/astrobee/commit/8a80326356bb67ab919e23ab2f696670914e96a3

2020-10-17 03:19 UTC, trey0 commented on astrobee/commands/freeFlyerPlanSchema.json
> +          "notes": "This field was originally intended to allow specifying what reference frame the center of mass is expressed in. However, in the current implementation, the reference frame is hard
Ok, fixed in https://github.com/trey0/astrobee/commit/8a80326356bb67ab919e23ab2f696670914e96a3

2020-10-19 19:02 UTC, kbrowne15 approved these changes

2020-10-20 18:27 UTC, merged