make CI work on ros2 branch
nasa/astrobee pull request #605
Opened 2022-12-07 21:48 UTC by trey0

This is a temporary fix for the CI on the `ros2` branch until we remove the universal package stuff. It installs Jinja2 in the `astrobee_base` Docker image (again, temporarily) and fixes some issues in `configure.sh`.

Because the CI testing uses the base Docker image, this PR is not expected to initially pass CI testing, but it should pass after it's merged and the CI action to push the base Docker image is manually invoked. (You can see it passed CI testing here https://github.com/trey0/astrobee/actions/runs/3641004701 )

2022-12-12 19:32 UTC, marinagmoreira requested changes

2022-12-12 21:48 UTC, trey0 commented on scripts/docker/astrobee_base.Dockerfile
> +RUN apt-get update \
Ok! That actually would have been a simpler place to start... I avoided it to stick to the existing convention about how the Dockerfile stages are organized. But if we can break that slightly to keep it simpler, so much the better. Fixed in bb80b2f.

2022-12-12 21:50 UTC, merged

2022-12-12 22:37 UTC, marinagmoreira commented
I didn't see the CI run in this PR (that's why I didn't approve it). Either something else broke or Github is being slow in starting the CI (has happened in the past)

2022-12-12 22:43 UTC, marinagmoreira commented
The CI is running in https://github.com/nasa/astrobee/pull/600 after I merged the changes in, hopefully it validates this PR

2022-12-13 00:46 UTC, trey0 commented
> The CI is running in #600 after I merged the changes in, hopefully it validates this PR

Yeah, I didn't merge it until after it had passed CI here https://github.com/trey0/astrobee/actions/runs/3679394555